app/campanas/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, DateTimeField, HiddenField, SubmitField
from wtforms.validators import DataRequired
from .. models import Campana


class CampanaForm(FlaskForm):
    nombre = StringField('Nombre',
                         validators=[DataRequired(u"Debe ingresar el Nombre de la campaña")],
                         render_kw={"placeholder": u"Nombre de Campaña"})
    descripcion = StringField(u'Descripción',
                         validators=[DataRequired(u"Debe ingresar la descripción de la Campaña")],
                         render_kw={"placeholder": u"Descripción de la Campaña"})
    hashtag = StringField('hashtag',
                          render_kw={"placeholder": u"Hashtag"})
    screen_name = StringField('screen_name',
                          render_kw={"placeholder": "Screen Name"})
    rango_fechas = StringField('Rango Fechas',
                          validators=[DataRequired("Debe ingresar un rango de fechas")],
                          render_kw={"placeholder": "Rango de fechas y horas"})
    fecha_inicio = DateTimeField('Fecha de Inicio',
                        format="%Y-%m-%d %H:%M:%S",
                        validators=[DataRequired("Debe ingresar una fecha de inicio")])
    fecha_termino = DateTimeField('Fecha de Termino',
                        format="%Y-%m-%d %H:%M:%S",
                        validators=[DataRequired(u"Debe ingresar una fecha de término")])
    submit = SubmitField('Guardar')

    def validate(self):
        validation = FlaskForm.validate(self)
        if not validation:
            return False

        if not self.hashtag.data and not self.screen_name.data:
            self.hashtag.errors.append(u'Debe ingresar un Hashtag o un Screen Name')
            self.screen_name.errors.append(u'Debe ingresar un Hashtag o un Screen Name')
            return False
        return True


class AnalisisForm(FlaskForm):
    hashtag = StringField('hashtag',
                          render_kw={"placeholder": "Hashtag"})
    screen_name = StringField('screen_name',
                          render_kw={"placeholder": "Screen Name"})
    rango_fechas = StringField('Rango Fechas',
                          validators=[DataRequired("Debe ingresar un rango de fechas")],
                          render_kw={"placeholder": "Rango de fechas y horas"})
    fecha_inicio = DateTimeField('Seleccione Fecha Inicio',
                             format="%Y-%m-%d %H:%M:%S",
                             validators=[DataRequired("Debe ingresar un rango de fechas")],
                             render_kw={"placeholder": "Desde el..."})
    fecha_termino = DateTimeField('Seleccione Fecha Término',
                              format="%Y-%m-%d %H:%M:%S",
                              validators=[DataRequired("Debe ingresar un rango de fechas")],
                              render_kw={"placeholder": "Hasta el..."})

    def validate(self):
        validation = FlaskForm.validate(self)
        if not validation:
            return False

        if not self.hashtag.data and not self.screen_name.data:
            self.hashtag.errors.append(u'Debe ingresar un Hashtag o un Screen Name')
            self.screen_name.errors.append(u'Debe ingresar un Hashtag o un Screen Name')
            return False
        return True

app/campanas/__init__.py
from flask import Blueprint

campanas = Blueprint('campanas', __name__)

from . import views

app/campanas/views.py
# -*- coding: utf-8 -*-
import json
import os
from datetime import datetime
from flask import render_template, flash, url_for, redirect, send_file, abort
from flask_login import login_required, current_user
from app.persistencia import elasticsearchutils
from app.utils import Utils

from . import campanas
from .. import db
from forms import CampanaForm, AnalisisForm
from ..models import Campana
from app.persistencia import mysqlutils
from app.utils import EstadosCampanas

import logging
from logging.config import fileConfig
fileConfig('logging_config.ini')
logger = logging.getLogger()

mysql = mysqlutils.Utils()

@campanas.route('/campanas/descarga_heatmap/<string:nombre>', methods=['GET', 'POST'])
@login_required
def descarga_heatmap(nombre):
    nombre_imagen = nombre + ".png"
    ruta_base = os.path.abspath("")
    return send_file(ruta_base + "/app/reportes/heatmaps/" + nombre_imagen, as_attachment=True)


@campanas.route('/campanas/resultados_campana/<int:id>', methods=['GET', 'POST'])
@login_required
def resultados_campana(id):
    campana = Campana.query.filter(Campana.id == id).first()
    if campana is not None and campana.user_id != current_user.id:
        Utils.check_admin()
    elif campana is not None and campana.estado == EstadosCampanas().FINALIZADA:
        resultado = mysql.notificacion_leida(id)
        if resultado:
            logger.info(u"Se leyó la notificación de la Campaña: <ID:%d>", id)
        else:
            logger.info(u"No se pudo actualizar el estado de la notificación para la Campaña: <ID:%d>", id)
    elif campana is None:
        abort(404)
    # Se cargan los datos para la navbar
    navbar_data = mysql.get_navbar_data()
    menu = Utils.init_menu()
    menu['treeview_campanas']['estado'] = 'active'
    menu['treeview_campanas']['consultar']['estado'] = 'active'


    # Totales en cantidad
    totales_acumulados = mysql.get_totales_acumulados(id, False, False)

    # Se calcula el total de tweets
    total_tweets = 0
    for total_acumulado in totales_acumulados:
        total_tweets += total_acumulado

    # Totales en cantidad (género masculino)
    totales_acumulados_male = mysql.get_totales_acumulados(id, False, 'male')
    # Se calcula el total de tweets
    total_tweets_male = 0
    if totales_acumulados_male is not None:
        for total_acumulado_male in totales_acumulados_male:
            total_tweets_male += total_acumulado_male

    # Totales en cantidad (género femenino)
    totales_acumulados_female = mysql.get_totales_acumulados(id, False, 'female')
    # Se calcula el total de tweets
    total_tweets_female = 0
    if totales_acumulados_female is not None:
        for total_acumulado_female in totales_acumulados_female:
            total_tweets_female += total_acumulado_female

    # Totales en cantidad (género sin determinar)
    totales_acumulados_unknown = mysql.get_totales_acumulados(id, False, 'unknown')
    # Se calcula el total de tweets
    total_tweets_unknown = 0
    if totales_acumulados_unknown is not None:
        for total_acumulado_unknown in totales_acumulados_unknown:
            total_tweets_unknown += total_acumulado_unknown

    # Gráfico Polar
    datos_polar = totales_acumulados

    # Totales en %
    datos_piechart = mysql.get_totales_acumulados(id, True, False)

    # Totales en % (género masculino)
    datos_piechart_male = None if total_tweets_male == 0 else mysql.get_totales_acumulados(id, True, 'male')

    # Totales en % (género femenino)
    datos_piechart_female = None if total_tweets_female == 0 else mysql.get_totales_acumulados(id, True, 'female')

    # Totales en % (género indeterminado)
    # datos_piechart_unknown = None if total_tweets_unknown == 0 else mysql.get_totales_acumulados(id, True, 'unknown')
    datos_piechart_unknown = mysql.get_totales_acumulados(id, True, 'unknown')

    els = elasticsearchutils.Utils()
    parametros = {
        'hashtag': campana.hashtag,
        'screen_name': campana.screen_name,
        'fecha_inicio_es': campana.fecha_inicio.strftime('%a %b %d %H:%M:%S +0000 %Y'),
        'fecha_termino_es': campana.fecha_termino.strftime('%a %b %d %H:%M:%S +0000 %Y'),
    }

    resultados = els.busqueda_estandar(parametros)

    return render_template('campanas/resultados.html',
                           title=u'Resultado Campaña',
                           campana=campana,
                           id_campana=str(campana.id),
                           datos_polar=datos_polar,
                           datos_piechart=datos_piechart,
                           datos_piechart_male=datos_piechart_male,
                           datos_piechart_female=datos_piechart_female,
                           datos_piechart_unknown=datos_piechart_unknown,
                           comunas=resultados['comunas'],
                           totales=resultados['totales'],
                           total_tweets=total_tweets,
                           total_tweets_male=total_tweets_male,
                           total_tweets_female=total_tweets_female,
                           total_tweets_unknown=total_tweets_unknown,
                           totales_acumulados_male=totales_acumulados_male,
                           totales_acumulados_female=totales_acumulados_female,
                           totales_acumulados_unknown=totales_acumulados_unknown,
                           menu=menu,
                           navbar_data=navbar_data)


@campanas.route('/campanas/editar_campana/<int:id>', methods=['GET', 'POST'])
@login_required
def editar_campana(id):
    # Esto asegura que solo un admin o el propio usuario pueda modificar sus datos
    campana = Campana.query.get_or_404(id)
    if current_user.id != campana.user_id:
        Utils.check_admin()

    # Se cargan los datos para la navbar
    navbar_data = mysql.get_navbar_data()
    menu = Utils.init_menu()
    menu['treeview_campanas']['estado'] = 'active'
    menu['treeview_campanas']['crear']['estado'] = 'active'

    crear_campana = False

    form = CampanaForm(obj=campana)
    if form.validate_on_submit():
        campana.nombre = form.nombre.data
        campana.descripcion = form.descripcion.data
        campana.hashtag = form.hashtag.data
        campana.screen_name = form.screen_name.data
        campana.fecha_inicio = form.fecha_inicio.data
        campana.fecha_termino = form.fecha_termino.data

        if datetime.now() >= form.fecha_termino.data:
            campana.estado = EstadosCampanas().PROCESANDO_RESULTADOS
        elif form.fecha_inicio.data <= datetime.now() < form.fecha_termino.data:
            campana.estado = EstadosCampanas().EN_CURSO
        else:
            campana.estado = EstadosCampanas().PROGRAMADA

        db.session.add(campana)
        db.session.commit()
        flash(u'La Campaña ha sido editada', 'success')

        return redirect(url_for('campanas.list_campanas'))

    return render_template('campanas/campana.html', crear_campana=crear_campana,
                           form=form, title=u"Editar Campaña", menu=menu, navbar_data=navbar_data)


@campanas.route('/campanas/borrar_campana/<int:id>', methods=['GET', 'POST'])
@login_required
def borrar_campana(id):
    try:
        campana = Campana.query.get_or_404(id)
        db.session.delete(campana)
        db.session.commit()
        flash(u'Se ha eliminado la Campaña', 'success')
    except:
        flash(u'Error: no fue posible eliminar la Campaña', 'error')
    return redirect(url_for('campanas.list_campanas'))


@campanas.route("/campanas/nueva", methods=['GET', 'POST'])
@login_required
def crear_campana():
    # Se cargan los datos para la navbar
    navbar_data = mysql.get_navbar_data()
    menu = Utils.init_menu()
    menu['treeview_campanas']['estado'] = 'active'
    menu['treeview_campanas']['crear']['estado'] = 'active'

    crear_campana = True

    form = CampanaForm()
    if form.validate_on_submit():

        if datetime.now() >= form.fecha_termino.data:
            estado = EstadosCampanas().PROCESANDO_RESULTADOS
        elif form.fecha_inicio.data <= datetime.now() < form.fecha_termino.data:
            estado = EstadosCampanas().EN_CURSO
        else:
            estado = EstadosCampanas().PROGRAMADA

        campana = Campana(
                    user_id=current_user.id,
                    nombre=form.nombre.data,
                    descripcion=form.descripcion.data,
                    hashtag=form.hashtag.data,
                    screen_name=form.screen_name.data,
                    fecha_inicio=form.fecha_inicio.data,
                    fecha_termino=form.fecha_termino.data,
                    finalizacion_notificada=False,
                    estado=estado)

        try:
            db.session.add(campana)
            db.session.commit()
            flash(u'Se ha creado una nueva Campaña', 'success')
        except:
            flash(u'Error: no fue posible crear una Campaña', 'error')

        # Redirige al mantenedor de Campañas
        return redirect(url_for('campanas.list_campanas'))

    return render_template('campanas/campana.html', crear_campana=crear_campana,
                           form=form, title=u'Crear Campaña', menu=menu, navbar_data=navbar_data)


@campanas.route("/campanas/gestion", methods=['GET', 'POST'])
@login_required
def list_campanas():
    navbar_data = mysql.get_navbar_data()
    menu = Utils.init_menu()
    menu['treeview_campanas']['estado'] = 'active'
    menu['treeview_campanas']['consultar']['estado'] = 'active'

    if current_user.es_admin == True:
        campanas = Campana.query.all()
    else:
        campanas = Campana.query.filter(Campana.user_id == current_user.id).all()


    return render_template('campanas/campanas.html',
                           campanas=campanas, title='Campanas', menu=menu, navbar_data=navbar_data)


@campanas.route("/campanas/analisis", methods=['GET', 'POST'])
@login_required
def analisis():
    navbar_data = mysql.get_navbar_data()

app/templates/campanas/analisis.html
{% extends "adminlte/base.html" %}
{% import "adminlte/layout.html" as layout with context %}
{% import "adminlte/widgets.html" as widgets with context %}

{% block navbar %}
    {% include "navbar_estandar.html" %}
{%- endblock navbar %}

{% block sidebar -%}
    {% include "sidebar_estandar.html" %}
{%- endblock sidebar %}

{% block content_header -%}
          <h1>
            Análisis
            <small>en Tiempo Real</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-tasks"></i> Campañas</a></li>
            <li class="active">Análisis en Tiempo Real</li>
          </ol>
{%- endblock content_header %}
{% block content -%}
    {% if parametros %}

    <div class="col-lg-12 col-xs-12">
        <div class="box box-success">
            <div class="box-header with-border">
              <h3 class="box-title">Resultado Análisis</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
              </div>
            </div>

            <div class="box-body">
                  <dl class="dl-horizontal">
                    <dt>Hashtag:</dt>
                    <dd>{%  if parametros.hashtag %}#{{ parametros.hashtag }}{%  else %}TODOS{%  endif %}</dd>
                    <dt>Screen Name:</dt>
                    <dd>{%  if parametros.screen_name %}@{{ parametros.screen_name }}{%  else %}TODOS{%  endif %}</dd>
                    <dt>Tweets creados desde:</dt>
                    <dd>{{ parametros.fecha_inicio }}</dd>
                    <dt>Tweets creados hasta:</dt>
                    <dd>{{ parametros.fecha_termino }}</dd>
                  </dl>
            </div>
        </div>
    </div>

    <div class="col-lg-12 col-xs-12">
        <div class="box box-success">
        <div class="box-header with-border">
          <h3 class="box-title">Se encontró la cantidad de {{ totales.suma_total }} Tweet(s):</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          </div>
        </div>
        <div class="box-body table-responsive">
        <table id="analisis" class="table table-bordered table-striped" width="100%">
            <thead>
                    <th></th>
                    <th>Alegría</th>
                    <th>Ira</th>
                    <th>Miedo</th>
                    <th>Asco</th>
                    <th>Sorpresa</th>
                    <th>Tristeza</th>
            </thead>
            <tbody>
                    {% for nombre_comuna,comuna in comunas.items() %}
                        <tr>
                            <td>{{ nombre_comuna }}</td>
                            <td>{% if comuna.sentimientos.alegria %}{{ (comuna.sentimientos.alegria * 100 / comuna.total)|round(1) }}%{% else %} 0 {%  endif %}</td>
                            <td>{% if comuna.sentimientos.ira %}{{ (comuna.sentimientos.ira * 100 / comuna.total)|round(1) }}%{% else %} 0 {%  endif %}</td>
                            <td>{% if comuna.sentimientos.miedo %}{{ (comuna.sentimientos.miedo * 100 / comuna.total)|round(1) }}%{% else %} 0 {%  endif %}</td>
                            <td>{% if comuna.sentimientos.asco %}{{ (comuna.sentimientos.asco * 100 / comuna.total)|round(1) }}%{% else %} 0 {%  endif %}</td>
                            <td>{% if comuna.sentimientos.sorpresa %}{{ (comuna.sentimientos.sorpresa * 100 / comuna.total)|round(1) }}%{% else %} 0 {%  endif %}</td>
                            <td>{% if comuna.sentimientos.tristeza %}{{ (comuna.sentimientos.tristeza * 100 / comuna.total)|round(1) }}%{% else %} 0 {%  endif %}</td>
                        </tr>
                    {% endfor %}
            </tbody>
        </table>
        </div>
      </div>
    </div>


<div class="row">
        <div class="col-lg-offset-4 col-lg-4 col-xs-offset-4 col-xs-4">
            <a href="{{url_for('campanas.analisis')}}" class="btn btn-block btn-primary btn-lg">Volver</a>
        </div>
</div>

    {% else %}


    <div class="row">
        <div class="col-xs-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Ingrese los datos para efectuar la búsqueda</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="" method="post" name="analisis">
              {{ form.hidden_tag() }}
              <div class="box-body">
                <div class="input-group">
                    <span class="input-group-addon">#</span>
                    {{ form.hashtag(class="form-control") }}
                </div>
                <br>
                <div class="input-group">
                    <span class="input-group-addon">@</span>
                    {{ form.screen_name(class="form-control") }}
                </div>
                <br>
                <div class="input-group {% if form.rango_fechas.errors %}has-error{% endif %}">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    {{ form.rango_fechas(class="form-control daterange") }}
                    {% if form.rango_fechas.errors %}
                        {% for error in form.rango_fechas.errors %}
                            <span class="help-block">*{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="input-group hidden">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    {{ form.fecha_inicio(class="form-control") }}
                </div>
                <div class="input-group hidden">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    {{ form.fecha_termino(class="form-control") }}
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Buscar</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </div>
    </div>

    {%  endif %}
{%- endblock content %}


{% block extra_styles -%}
    <link href="{{ adminlte_find_resource('css/daterangepicker/daterangepicker-bs3.css', cdn='local', use_minified=False) }}" rel="stylesheet" type="text/css" />
    <link href="{{ adminlte_find_resource('js/plugins/datatables/jquery.dataTables.css', cdn='local', use_minified=False) }}" rel="stylesheet" type="text/css" />
    <link href="{{ adminlte_find_resource('js/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css', cdn='local', use_minified=False) }}" rel="stylesheet" type="text/css" />
{%- endblock extra_styles %}

{% block extra_scripts -%}

        <!-- DataTables -->
        <script src="{{ adminlte_find_resource('js/plugins/datatables/jquery.dataTables.js', cdn='local', use_minified=False) }}"></script>
        <script src="{{ adminlte_find_resource('js/plugins/datatables/extensions/Responsive/js/dataTables.responsive.js', cdn='local', use_minified=False) }}"></script>
        <script>
          $(document).ready(function(){

            var table = $('#analisis').DataTable({
                responsive: true,
                language: {
                  "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                }
            });

            table
            .draw();
        });
        </script>

    <script src="{{ adminlte_find_resource('js/plugins/daterangepicker/moment.js', cdn='local') }}"></script>
    <script src="{{ adminlte_find_resource('js/plugins/daterangepicker/daterangepicker.js', cdn='local', use_minified=False)  }}"></script>

    <script>
       $(function() {
            //Date range picker with time picker
            $(".daterange").daterangepicker({
                showDropdowns: true,
                autoUpdateInput: false,
                timePicker: true,
                timePickerIncrement: 1,
                timePicker24Hour: true,
                dateLimit: {
                    "days": 31
                },
                locale: {
                    format: 'DD/MM/YYYY h:mm A',
                    applyLabel: 'Aceptar',
                    cancelLabel: 'Cancelar',
                    fromLabel: 'Desde',
                    toLabel: 'Hasta',
                    daysOfWeek: [
                        "Do",
                        "Lu",
                        "Ma",
                        "Mi",
                        "Ju",
                        "Vi",
                        "Sa"
                    ],
                    monthNames: [
                        "Enero",
                        "Febrero",
                        "Marzo",
                        "Abril",
                        "Mayo",
                        "Junio",
                        "Julio",
                        "Agosto",
                        "Septiembre",
                        "Octubre",
                        "Noviembre",
                        "Diciembre"
                    ],
                    firstDay: 1
                },
                minDate: "17/12/2017"
            });

            $('.daterange').on('apply.daterangepicker', function(ev, picker) {
                $(this).val('Desde el ' + picker.startDate.format('DD/MM/YYYY HH:mm') + ' hasta el ' + picker.endDate.format('DD/MM/YYYY HH:mm'));
                $('#fecha_inicio').val(picker.startDate.format('YYYY-MM-DD HH:mm:ss'));
                $('#fecha_termino').val(picker.endDate.format('YYYY-MM-DD HH:mm:ss'));

            });

            $('.daterange').on('cancel.daterangepicker', function(ev, picker) {
              $(this).val('');
            });
        });
    </script>

{%- endblock extra_scripts %}

app/templates/campanas/campanas.html
{% extends "adminlte/base.html" %}
{% import "adminlte/layout.html" as layout with context %}
{% import "adminlte/widgets.html" as widgets with context %}

{% block navbar %}
    {% include "navbar_estandar.html" %}
{%- endblock navbar %}

{% block sidebar -%}
    {% include "sidebar_estandar.html" %}
{%- endblock sidebar %}

{% block content_header -%}
          <h1>
            Campañas
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-tasks"></i> Campañas</a></li>
            <li class="active">Gestionar Campañas</li>
          </ol>
{%- endblock content_header %}
{% block content -%}


<div class="content-section">
    <div class="outer">
      <div class="middle">
        <div class="inner">
          {% if campanas %}
            <hr class="intro-divider">
            <div class="box">
             <div class="box-body table-responsive">
              <table id="campanas" class="table table-bordered table-striped" width="100%">
                <thead>
                  <tr>
                    <th> ID </th>
                    <th> Nombre </th>
                    <th> Descripción </th>
                    <th> Hashtag </th>
                    <th> Screen Name </th>
                    <th> Fecha Inicio </th>
                    <th> Fecha Término </th>
                    <th> Estado </th>
                    <th> Creado por </th>
                    <th data-priority="1"> Acciones </th>
                  </tr>
                </thead>
                <tbody>
                {% for campana in campanas %}
                  <tr>
                    <td> {{ campana.id }} </td>
                    <td> {{ campana.nombre }} </td>
                    <td> {{ campana.descripcion }} </td>
                    <td> {% if campana.hashtag %}{{ campana.hashtag }} {% else %} - {% endif %}</td>
                    <td> {% if campana.screen_name %}{{ campana.screen_name }} {% else %} - {% endif %}</td>
                    <td> {{ campana.fecha_inicio.strftime('%d/%m/%Y %H:%M') }} </td>
                    <td> {{ campana.fecha_termino.strftime('%d/%m/%Y %H:%M') }} </td>
                    <td> {{ campana.estado.upper().replace("_", " ") }} </td>
                    <td> {{ campana.user.username }} </td>
                    <td style="min-width:120px">
                      {% if campana.estado == 'finalizada'%}
                        <a href="{{ url_for('campanas.resultados_campana', id=campana.id) }}">
                          <i class="fa fa-info-circle"></i> Ver Resultados
                        </a>
                      {% elif campana.estado == 'procesando_resultados'  %}
                        <a href="{{ url_for('campanas.resultados_campana', id=campana.id) }}">
                          <i class="fa fa-info-circle"></i> Ver Avance
                        </a><br>
                      {% elif campana.estado == 'programada' or campana.estado == 'en_curso' %}
                        <a href="{{ url_for('campanas.resultados_campana', id=campana.id) }}">
                          <i class="fa fa-info-circle"></i> Ver Avance
                        </a><br>
                        <a href="{{ url_for('campanas.editar_campana', id=campana.id) }}">
                          <i class="fa fa-pencil"></i> Editar
                        </a><br>
                        <a href="{{ url_for('campanas.borrar_campana', id=campana.id) }}">
                          <i class="fa fa-trash"></i> Eliminar
                        </a>
                      {% endif %}
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
             </div>
            </div>
            <div style="text-align: center">
          {% else %}
            <div style="text-align: center">
              <h3> No se han agregado Campañas. </h3>
              <hr class="intro-divider">
          {% endif %}

          </div>
        </div>
      </div>
  </div>
  </div>
  </div>

{%- endblock content %}

  {% block extra_styles %}
    <link href="{{ adminlte_find_resource('js/plugins/datatables/jquery.dataTables.css', cdn='local', use_minified=False) }}" rel="stylesheet" type="text/css" />
    <link href="{{ adminlte_find_resource('js/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css', cdn='local', use_minified=False) }}" rel="stylesheet" type="text/css" />
  {% endblock extra_styles %}


{% block extra_scripts %}

<!-- DataTables -->
<script src="{{ adminlte_find_resource('js/plugins/datatables/jquery.dataTables.js', cdn='local', use_minified=False) }}"></script>
<script src="{{ adminlte_find_resource('js/plugins/datatables/extensions/Responsive/js/dataTables.responsive.js', cdn='local', use_minified=False) }}"></script>


<script>
  $(document).ready(function(){

    var table = $('#campanas').DataTable({
        responsive: true,
        language: {
          "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
        }
    });

    table
    .column( '0:visible' )
    .order( 'desc' )
    .draw();
});
</script>

{% endblock extra_scripts %}